### ISSUE TITLE
not able to fetch the contacts list. Need help in understanding the way we create the config.js file.

### ISSUE THREAD

**Issue by hrshtpnt** [zafar-saleem/blockchain-tutorial#3]
I was going through the tutorial and the steps are very descriptive. I was able to follow each step until the last one and need some help. Please explain how did we create the config.js file. Where do we copy it from @zafar-saleem ?

When running I get this error, I am not sure if the config file is causing this error.

```
index.js:297 Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at ABICoder.push../node_modules/web3-eth-abi/lib/index.js.ABICoder.decodeParametersWith (index.js:297:1)
    at ABICoder.push../node_modules/web3-eth-abi/lib/index.js.ABICoder.decodeParameters (index.js:284:1)
    at Contract.push../node_modules/web3-eth-contract/lib/index.js.Contract._decodeMethodReturn (index.js:481:1)
    at Method.outputFormatter (index.js:788:1)
    at Method.push../node_modules/web3-core-method/lib/index.js.Method.formatOutput (index.js:147:1)
    at sendTxCallback (index.js:530:1)
    at cb (util.js:689:1)
    at Item.push../node_modules/process/browser.js.Item.run (browser.js:153:1)
    at drainQueue (browser.js:123:1)
```

**Comment by dplamenov** [comment]
@hrshtpnt How you fixed this error?

**Comment by zafar-saleem** [comment]
@hrshtpnt copy `abi` part from `contracts/build/contracts/Contacts.json` file.

**Comment by hrshtpnt** [comment]
@zafar-saleem @dplamenov  I was not configuring my metamask with ganache but using the global network causing this error.
That's why the error said, "did it run Out of Gas?

Hope that helps!
